### ISSUE TITLE
Clicking a text widget causes a crash.

### ISSUE THREAD

**Issue by Blotz** [shade40/Celadon#1]
Hello again! Sorry for all the issues :P. I'm checking out new TUI libraries and I keep running into small bugs.

So clicking on a text widget calls the `on_click()` method which checks to see if `self.app` is None.
This causes an `AttributeError` because the text class doesn't have an attribute called app.

The code used to get this bug:

```python
import celadon
from celadon import Page, Tower, Row, Button, Text


app = celadon.Application("TEST APP")

app += Page(
    Tower(
        Row(
            Text("I mimick the web"),
            Text("For it cannot mimick me"),
            eid="header",
        ),
        Tower(Text.lorem(), eid="body", group="center"),
        Row(
            Button("Ctrl-C : Quit"),
            Button("F12 : Screenshot"),
            eid="footer",
        ),
    ),
    rules="""
    Tower#body:
        frame: [null, heavy, null, heavy]

    Row#header, Row#footer:
        alignment: [center, start]
        height: 1
""",
)
app.run()
```

**Comment by bczsalba** [comment]
Guess I never considered _not_ using the context manager syntax for application construction! Both syntaxes should work now.
